#ifndef AMBIENT_CONSTANTS_H
#define AMBIENT_CONSTANTS_H

#define AMBIENT_CONVERT 0
#define AMBIENT_CROP 1
#define AMBIENT_DOWNSAMPLE 2
#define AMBIENT_UPSAMPLE 3
#define AMBIENT_SMOOTH 4
#define AMBIENT_COMPOSE 5

#define AMBIENT_SDR 0
#define AMBIENT_HDR10 1
#define AMBIENT_SCRGB 2

#endif
